// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetMessage.proto

package LockstepProto;

public interface C2SLockStepInitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LockstepProto.C2SLockStepInit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool singlePlayer = 1;</code>
   */
  boolean getSinglePlayer();

  /**
   * <code>bool stopLockStep = 2;</code>
   */
  boolean getStopLockStep();
}
