// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetMessage.proto

package LockstepProto;

public interface C2SLockStepOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LockstepProto.C2SLockStep)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.LockstepProto.Command c = 1;</code>
   */
  boolean hasC();
  /**
   * <code>.LockstepProto.Command c = 1;</code>
   */
  LockstepProto.Command getC();
  /**
   * <code>.LockstepProto.Command c = 1;</code>
   */
  LockstepProto.CommandOrBuilder getCOrBuilder();
}
