// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetMessage.proto

package LockstepProto;

public interface C2SStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LockstepProto.C2SState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 state = 1;</code>
   */
  int getState();
}
