// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LSMessage.proto

package LockstepProto;

public interface CoordinateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LockstepProto.Coordinate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>sint32 x = 1;</code>
   */
  int getX();

  /**
   * <code>sint32 y = 2;</code>
   */
  int getY();
}
