// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetMessage.proto

package LockstepProto;

public interface S2CLockStepOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LockstepProto.S2CLockStep)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .LockstepProto.Frame f = 1;</code>
   */
  java.util.List<Frame>
      getFList();
  /**
   * <code>repeated .LockstepProto.Frame f = 1;</code>
   */
  Frame getF(int index);
  /**
   * <code>repeated .LockstepProto.Frame f = 1;</code>
   */
  int getFCount();
  /**
   * <code>repeated .LockstepProto.Frame f = 1;</code>
   */
  java.util.List<? extends FrameOrBuilder>
      getFOrBuilderList();
  /**
   * <code>repeated .LockstepProto.Frame f = 1;</code>
   */
  FrameOrBuilder getFOrBuilder(
          int index);
}
