// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetMessage.proto

package LockstepProto;

public interface S2CStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LockstepProto.S2CState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>sint64 roleId = 1;</code>
   */
  long getRoleId();

  /**
   * <code>sint32 state = 2;</code>
   */
  int getState();
}
