// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LSMessage.proto

package LockstepProto;

public interface SelectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LockstepProto.Selection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated uint32 agentId = 1;</code>
   */
  java.util.List<Integer> getAgentIdList();
  /**
   * <code>repeated uint32 agentId = 1;</code>
   */
  int getAgentIdCount();
  /**
   * <code>repeated uint32 agentId = 1;</code>
   */
  int getAgentId(int index);
}
