// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LSMessage.proto

package LockstepProto;

public interface BattleActorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LockstepProto.BattleActor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 roleId = 1;</code>
   */
  long getRoleId();

  /**
   * <code>sint32 iq = 2;</code>
   */
  int getIq();

  /**
   * <code>sint32 agi = 3;</code>
   */
  int getAgi();

  /**
   * <code>sint32 str = 4;</code>
   */
  int getStr();

  /**
   * <code>repeated sint32 cardIds = 5;</code>
   */
  java.util.List<Integer> getCardIdsList();
  /**
   * <code>repeated sint32 cardIds = 5;</code>
   */
  int getCardIdsCount();
  /**
   * <code>repeated sint32 cardIds = 5;</code>
   */
  int getCardIds(int index);

  /**
   * <code>sint32 school = 6;</code>
   */
  int getSchool();

  /**
   * <code>string roleName = 7;</code>
   */
  String getRoleName();
  /**
   * <code>string roleName = 7;</code>
   */
  com.google.protobuf.ByteString
      getRoleNameBytes();

  /**
   * <code>sint32 rankId = 8;</code>
   */
  int getRankId();

  /**
   * <code>sint32 starCount = 9;</code>
   */
  int getStarCount();

  /**
   * <code>sint32 schoolLv = 10;</code>
   */
  int getSchoolLv();
}
