// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetMessage.proto

package LockstepProto;

public interface C2SReconnectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LockstepProto.C2SReconnect)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>sint64 roleId = 1;</code>
   */
  long getRoleId();
}
