// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LSMessage.proto

package LockstepProto;

public interface DefaultDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LockstepProto.DefaultData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *TData
   * </pre>
   *
   * <code>uint32 type = 1;</code>
   */
  int getType();

  /**
   * <code>int64 anyIntAndBool = 2;</code>
   */
  long getAnyIntAndBool();

  /**
   * <code>bytes bytesAndString = 3;</code>
   */
  com.google.protobuf.ByteString getBytesAndString();

  public DefaultData.ValueCase getValueCase();
}
