// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LSMessage.proto

package LockstepProto;

public interface FrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LockstepProto.Frame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 InfluenceFrameCount = 1;</code>
   */
  int getInfluenceFrameCount();

  /**
   * <code>repeated bytes commands = 2;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getCommandsList();
  /**
   * <code>repeated bytes commands = 2;</code>
   */
  int getCommandsCount();
  /**
   * <code>repeated bytes commands = 2;</code>
   */
  com.google.protobuf.ByteString getCommands(int index);
}
