// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetMessage.proto

package LockstepProto;

/**
 * Protobuf type {@code LockstepProto.S2CBattleEnd}
 */
public  final class S2CBattleEnd extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:LockstepProto.S2CBattleEnd)
        S2CBattleEndOrBuilder {
private static final long serialVersionUID = 0L;
  // Use S2CBattleEnd.newBuilder() to construct.
  private S2CBattleEnd(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private S2CBattleEnd() {
    winners_ = emptyLongList();
    losers_ = emptyLongList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new S2CBattleEnd();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private S2CBattleEnd(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              winners_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            winners_.addLong(input.readSInt64());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              winners_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              winners_.addLong(input.readSInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 16: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              losers_ = newLongList();
              mutable_bitField0_ |= 0x00000002;
            }
            losers_.addLong(input.readSInt64());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
              losers_ = newLongList();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              losers_.addLong(input.readSInt64());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        winners_.makeImmutable(); // C
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        losers_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return LockstepProto.NetMessageOuterClass.internal_static_LockstepProto_S2CBattleEnd_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return LockstepProto.NetMessageOuterClass.internal_static_LockstepProto_S2CBattleEnd_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            S2CBattleEnd.class, Builder.class);
  }

  public static final int WINNERS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.LongList winners_;
  /**
   * <code>repeated sint64 winners = 1;</code>
   */
  public java.util.List<Long>
      getWinnersList() {
    return winners_;
  }
  /**
   * <code>repeated sint64 winners = 1;</code>
   */
  public int getWinnersCount() {
    return winners_.size();
  }
  /**
   * <code>repeated sint64 winners = 1;</code>
   */
  public long getWinners(int index) {
    return winners_.getLong(index);
  }
  private int winnersMemoizedSerializedSize = -1;

  public static final int LOSERS_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.LongList losers_;
  /**
   * <code>repeated sint64 losers = 2;</code>
   */
  public java.util.List<Long>
      getLosersList() {
    return losers_;
  }
  /**
   * <code>repeated sint64 losers = 2;</code>
   */
  public int getLosersCount() {
    return losers_.size();
  }
  /**
   * <code>repeated sint64 losers = 2;</code>
   */
  public long getLosers(int index) {
    return losers_.getLong(index);
  }
  private int losersMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getWinnersList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(winnersMemoizedSerializedSize);
    }
    for (int i = 0; i < winners_.size(); i++) {
      output.writeSInt64NoTag(winners_.getLong(i));
    }
    if (getLosersList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(losersMemoizedSerializedSize);
    }
    for (int i = 0; i < losers_.size(); i++) {
      output.writeSInt64NoTag(losers_.getLong(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < winners_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeSInt64SizeNoTag(winners_.getLong(i));
      }
      size += dataSize;
      if (!getWinnersList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      winnersMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < losers_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeSInt64SizeNoTag(losers_.getLong(i));
      }
      size += dataSize;
      if (!getLosersList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      losersMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof S2CBattleEnd)) {
      return super.equals(obj);
    }
    S2CBattleEnd other = (S2CBattleEnd) obj;

    if (!getWinnersList()
        .equals(other.getWinnersList())) return false;
    if (!getLosersList()
        .equals(other.getLosersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getWinnersCount() > 0) {
      hash = (37 * hash) + WINNERS_FIELD_NUMBER;
      hash = (53 * hash) + getWinnersList().hashCode();
    }
    if (getLosersCount() > 0) {
      hash = (37 * hash) + LOSERS_FIELD_NUMBER;
      hash = (53 * hash) + getLosersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static S2CBattleEnd parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static S2CBattleEnd parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static S2CBattleEnd parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static S2CBattleEnd parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static S2CBattleEnd parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static S2CBattleEnd parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static S2CBattleEnd parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static S2CBattleEnd parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static S2CBattleEnd parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static S2CBattleEnd parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static S2CBattleEnd parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static S2CBattleEnd parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(S2CBattleEnd prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code LockstepProto.S2CBattleEnd}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LockstepProto.S2CBattleEnd)
      LockstepProto.S2CBattleEndOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LockstepProto.NetMessageOuterClass.internal_static_LockstepProto_S2CBattleEnd_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LockstepProto.NetMessageOuterClass.internal_static_LockstepProto_S2CBattleEnd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              S2CBattleEnd.class, Builder.class);
    }

    // Construct using LockstepProto.S2CBattleEnd.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      winners_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      losers_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return LockstepProto.NetMessageOuterClass.internal_static_LockstepProto_S2CBattleEnd_descriptor;
    }

    @Override
    public S2CBattleEnd getDefaultInstanceForType() {
      return S2CBattleEnd.getDefaultInstance();
    }

    @Override
    public S2CBattleEnd build() {
      S2CBattleEnd result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public S2CBattleEnd buildPartial() {
      S2CBattleEnd result = new S2CBattleEnd(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        winners_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.winners_ = winners_;
      if (((bitField0_ & 0x00000002) != 0)) {
        losers_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.losers_ = losers_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof S2CBattleEnd) {
        return mergeFrom((S2CBattleEnd)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(S2CBattleEnd other) {
      if (other == S2CBattleEnd.getDefaultInstance()) return this;
      if (!other.winners_.isEmpty()) {
        if (winners_.isEmpty()) {
          winners_ = other.winners_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureWinnersIsMutable();
          winners_.addAll(other.winners_);
        }
        onChanged();
      }
      if (!other.losers_.isEmpty()) {
        if (losers_.isEmpty()) {
          losers_ = other.losers_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureLosersIsMutable();
          losers_.addAll(other.losers_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      S2CBattleEnd parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (S2CBattleEnd) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.LongList winners_ = emptyLongList();
    private void ensureWinnersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        winners_ = mutableCopy(winners_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated sint64 winners = 1;</code>
     */
    public java.util.List<Long>
        getWinnersList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(winners_) : winners_;
    }
    /**
     * <code>repeated sint64 winners = 1;</code>
     */
    public int getWinnersCount() {
      return winners_.size();
    }
    /**
     * <code>repeated sint64 winners = 1;</code>
     */
    public long getWinners(int index) {
      return winners_.getLong(index);
    }
    /**
     * <code>repeated sint64 winners = 1;</code>
     */
    public Builder setWinners(
        int index, long value) {
      ensureWinnersIsMutable();
      winners_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated sint64 winners = 1;</code>
     */
    public Builder addWinners(long value) {
      ensureWinnersIsMutable();
      winners_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated sint64 winners = 1;</code>
     */
    public Builder addAllWinners(
        Iterable<? extends Long> values) {
      ensureWinnersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, winners_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated sint64 winners = 1;</code>
     */
    public Builder clearWinners() {
      winners_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList losers_ = emptyLongList();
    private void ensureLosersIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        losers_ = mutableCopy(losers_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated sint64 losers = 2;</code>
     */
    public java.util.List<Long>
        getLosersList() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(losers_) : losers_;
    }
    /**
     * <code>repeated sint64 losers = 2;</code>
     */
    public int getLosersCount() {
      return losers_.size();
    }
    /**
     * <code>repeated sint64 losers = 2;</code>
     */
    public long getLosers(int index) {
      return losers_.getLong(index);
    }
    /**
     * <code>repeated sint64 losers = 2;</code>
     */
    public Builder setLosers(
        int index, long value) {
      ensureLosersIsMutable();
      losers_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated sint64 losers = 2;</code>
     */
    public Builder addLosers(long value) {
      ensureLosersIsMutable();
      losers_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated sint64 losers = 2;</code>
     */
    public Builder addAllLosers(
        Iterable<? extends Long> values) {
      ensureLosersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, losers_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated sint64 losers = 2;</code>
     */
    public Builder clearLosers() {
      losers_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:LockstepProto.S2CBattleEnd)
  }

  // @@protoc_insertion_point(class_scope:LockstepProto.S2CBattleEnd)
  private static final S2CBattleEnd DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new S2CBattleEnd();
  }

  public static S2CBattleEnd getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<S2CBattleEnd>
      PARSER = new com.google.protobuf.AbstractParser<S2CBattleEnd>() {
    @Override
    public S2CBattleEnd parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new S2CBattleEnd(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<S2CBattleEnd> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<S2CBattleEnd> getParserForType() {
    return PARSER;
  }

  @Override
  public S2CBattleEnd getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

