// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetMessage.proto

package LockstepProto;

public interface S2CLockStepInitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LockstepProto.S2CLockStepInit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 controlerID = 1;</code>
   */
  int getControlerID();
}
