// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LSMessage.proto

package LockstepProto;

public interface Vector3dOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LockstepProto.Vector3d)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>sint64 x = 1;</code>
   */
  long getX();

  /**
   * <code>sint64 y = 2;</code>
   */
  long getY();

  /**
   * <code>sint64 z = 3;</code>
   */
  long getZ();
}
