// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.noseparte.common.rpc.service;

/**
 * <pre>
 *响应参数
 * </pre>
 *
 * Protobuf type {@code idservice.UniqueNameResponse}
 */
public  final class UniqueNameResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:idservice.UniqueNameResponse)
    UniqueNameResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UniqueNameResponse.newBuilder() to construct.
  private UniqueNameResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UniqueNameResponse() {
    state_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new UniqueNameResponse();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UniqueNameResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            state_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.noseparte.common.rpc.service.Service.internal_static_idservice_UniqueNameResponse_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.noseparte.common.rpc.service.Service.internal_static_idservice_UniqueNameResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.noseparte.common.rpc.service.UniqueNameResponse.class, com.noseparte.common.rpc.service.UniqueNameResponse.Builder.class);
  }

  public static final int STATE_FIELD_NUMBER = 1;
  private int state_;
  /**
   * <code>.idservice.UniqueNameEnum state = 1;</code>
   */
  public int getStateValue() {
    return state_;
  }
  /**
   * <code>.idservice.UniqueNameEnum state = 1;</code>
   */
  public com.noseparte.common.rpc.service.UniqueNameEnum getState() {
    @SuppressWarnings("deprecation")
    com.noseparte.common.rpc.service.UniqueNameEnum result = com.noseparte.common.rpc.service.UniqueNameEnum.valueOf(state_);
    return result == null ? com.noseparte.common.rpc.service.UniqueNameEnum.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (state_ != com.noseparte.common.rpc.service.UniqueNameEnum.UNIQUE_NAME_DEFAULT.getNumber()) {
      output.writeEnum(1, state_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (state_ != com.noseparte.common.rpc.service.UniqueNameEnum.UNIQUE_NAME_DEFAULT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, state_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.noseparte.common.rpc.service.UniqueNameResponse)) {
      return super.equals(obj);
    }
    com.noseparte.common.rpc.service.UniqueNameResponse other = (com.noseparte.common.rpc.service.UniqueNameResponse) obj;

    if (state_ != other.state_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + state_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.noseparte.common.rpc.service.UniqueNameResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.noseparte.common.rpc.service.UniqueNameResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.noseparte.common.rpc.service.UniqueNameResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.noseparte.common.rpc.service.UniqueNameResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.noseparte.common.rpc.service.UniqueNameResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.noseparte.common.rpc.service.UniqueNameResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.noseparte.common.rpc.service.UniqueNameResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.noseparte.common.rpc.service.UniqueNameResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.noseparte.common.rpc.service.UniqueNameResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.noseparte.common.rpc.service.UniqueNameResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.noseparte.common.rpc.service.UniqueNameResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.noseparte.common.rpc.service.UniqueNameResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.noseparte.common.rpc.service.UniqueNameResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *响应参数
   * </pre>
   *
   * Protobuf type {@code idservice.UniqueNameResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:idservice.UniqueNameResponse)
      com.noseparte.common.rpc.service.UniqueNameResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.noseparte.common.rpc.service.Service.internal_static_idservice_UniqueNameResponse_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.noseparte.common.rpc.service.Service.internal_static_idservice_UniqueNameResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.noseparte.common.rpc.service.UniqueNameResponse.class, com.noseparte.common.rpc.service.UniqueNameResponse.Builder.class);
    }

    // Construct using com.noseparte.common.rpc.service.UniqueNameResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      state_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.noseparte.common.rpc.service.Service.internal_static_idservice_UniqueNameResponse_descriptor;
    }

    @Override
    public com.noseparte.common.rpc.service.UniqueNameResponse getDefaultInstanceForType() {
      return com.noseparte.common.rpc.service.UniqueNameResponse.getDefaultInstance();
    }

    @Override
    public com.noseparte.common.rpc.service.UniqueNameResponse build() {
      com.noseparte.common.rpc.service.UniqueNameResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.noseparte.common.rpc.service.UniqueNameResponse buildPartial() {
      com.noseparte.common.rpc.service.UniqueNameResponse result = new com.noseparte.common.rpc.service.UniqueNameResponse(this);
      result.state_ = state_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.noseparte.common.rpc.service.UniqueNameResponse) {
        return mergeFrom((com.noseparte.common.rpc.service.UniqueNameResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.noseparte.common.rpc.service.UniqueNameResponse other) {
      if (other == com.noseparte.common.rpc.service.UniqueNameResponse.getDefaultInstance()) return this;
      if (other.state_ != 0) {
        setStateValue(other.getStateValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.noseparte.common.rpc.service.UniqueNameResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.noseparte.common.rpc.service.UniqueNameResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int state_ = 0;
    /**
     * <code>.idservice.UniqueNameEnum state = 1;</code>
     */
    public int getStateValue() {
      return state_;
    }
    /**
     * <code>.idservice.UniqueNameEnum state = 1;</code>
     */
    public Builder setStateValue(int value) {
      state_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.idservice.UniqueNameEnum state = 1;</code>
     */
    public com.noseparte.common.rpc.service.UniqueNameEnum getState() {
      @SuppressWarnings("deprecation")
      com.noseparte.common.rpc.service.UniqueNameEnum result = com.noseparte.common.rpc.service.UniqueNameEnum.valueOf(state_);
      return result == null ? com.noseparte.common.rpc.service.UniqueNameEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>.idservice.UniqueNameEnum state = 1;</code>
     */
    public Builder setState(com.noseparte.common.rpc.service.UniqueNameEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }

      state_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.idservice.UniqueNameEnum state = 1;</code>
     */
    public Builder clearState() {

      state_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:idservice.UniqueNameResponse)
  }

  // @@protoc_insertion_point(class_scope:idservice.UniqueNameResponse)
  private static final com.noseparte.common.rpc.service.UniqueNameResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.noseparte.common.rpc.service.UniqueNameResponse();
  }

  public static com.noseparte.common.rpc.service.UniqueNameResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UniqueNameResponse>
      PARSER = new com.google.protobuf.AbstractParser<UniqueNameResponse>() {
    @Override
    public UniqueNameResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UniqueNameResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UniqueNameResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<UniqueNameResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public com.noseparte.common.rpc.service.UniqueNameResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

