// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetMessage.proto

package LockstepProto;

public interface C2SPullFrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LockstepProto.C2SPullFrame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 frameIdBegin = 1;</code>
   */
  int getFrameIdBegin();

  /**
   * <code>uint32 frameIdEnd = 2;</code>
   */
  int getFrameIdEnd();
}
