// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LSMessage.proto

package LockstepProto;

/**
 * Protobuf type {@code LockstepProto.Command}
 */
public  final class Command extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:LockstepProto.Command)
    CommandOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Command.newBuilder() to construct.
  private Command(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Command() {
    defaultData_ = java.util.Collections.emptyList();
    coordinate_ = java.util.Collections.emptyList();
    selection_ = java.util.Collections.emptyList();
    vector2D_ = java.util.Collections.emptyList();
    vector3D_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Command();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Command(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            controlerID_ = input.readInt32();
            break;
          }
          case 16: {

            inputCode_ = input.readInt32();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              defaultData_ = new java.util.ArrayList<LockstepProto.DefaultData>();
              mutable_bitField0_ |= 0x00000001;
            }
            defaultData_.add(
                input.readMessage(LockstepProto.DefaultData.parser(), extensionRegistry));
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              coordinate_ = new java.util.ArrayList<LockstepProto.Coordinate>();
              mutable_bitField0_ |= 0x00000002;
            }
            coordinate_.add(
                input.readMessage(LockstepProto.Coordinate.parser(), extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              selection_ = new java.util.ArrayList<LockstepProto.Selection>();
              mutable_bitField0_ |= 0x00000004;
            }
            selection_.add(
                input.readMessage(LockstepProto.Selection.parser(), extensionRegistry));
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              vector2D_ = new java.util.ArrayList<LockstepProto.Vector2d>();
              mutable_bitField0_ |= 0x00000008;
            }
            vector2D_.add(
                input.readMessage(LockstepProto.Vector2d.parser(), extensionRegistry));
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000010) != 0)) {
              vector3D_ = new java.util.ArrayList<LockstepProto.Vector3d>();
              mutable_bitField0_ |= 0x00000010;
            }
            vector3D_.add(
                input.readMessage(LockstepProto.Vector3d.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        defaultData_ = java.util.Collections.unmodifiableList(defaultData_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        coordinate_ = java.util.Collections.unmodifiableList(coordinate_);
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        selection_ = java.util.Collections.unmodifiableList(selection_);
      }
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        vector2D_ = java.util.Collections.unmodifiableList(vector2D_);
      }
      if (((mutable_bitField0_ & 0x00000010) != 0)) {
        vector3D_ = java.util.Collections.unmodifiableList(vector3D_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return LockstepProto.LSMessage.internal_static_LockstepProto_Command_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return LockstepProto.LSMessage.internal_static_LockstepProto_Command_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            LockstepProto.Command.class, LockstepProto.Command.Builder.class);
  }

  public static final int CONTROLERID_FIELD_NUMBER = 1;
  private int controlerID_;
  /**
   * <code>int32 controlerID = 1;</code>
   */
  public int getControlerID() {
    return controlerID_;
  }

  public static final int INPUTCODE_FIELD_NUMBER = 2;
  private int inputCode_;
  /**
   * <code>int32 inputCode = 2;</code>
   */
  public int getInputCode() {
    return inputCode_;
  }

  public static final int DEFAULTDATA_FIELD_NUMBER = 3;
  private java.util.List<LockstepProto.DefaultData> defaultData_;
  /**
   * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
   */
  public java.util.List<LockstepProto.DefaultData> getDefaultDataList() {
    return defaultData_;
  }
  /**
   * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
   */
  public java.util.List<? extends LockstepProto.DefaultDataOrBuilder> 
      getDefaultDataOrBuilderList() {
    return defaultData_;
  }
  /**
   * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
   */
  public int getDefaultDataCount() {
    return defaultData_.size();
  }
  /**
   * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
   */
  public LockstepProto.DefaultData getDefaultData(int index) {
    return defaultData_.get(index);
  }
  /**
   * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
   */
  public LockstepProto.DefaultDataOrBuilder getDefaultDataOrBuilder(
      int index) {
    return defaultData_.get(index);
  }

  public static final int COORDINATE_FIELD_NUMBER = 4;
  private java.util.List<LockstepProto.Coordinate> coordinate_;
  /**
   * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
   */
  public java.util.List<LockstepProto.Coordinate> getCoordinateList() {
    return coordinate_;
  }
  /**
   * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
   */
  public java.util.List<? extends LockstepProto.CoordinateOrBuilder> 
      getCoordinateOrBuilderList() {
    return coordinate_;
  }
  /**
   * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
   */
  public int getCoordinateCount() {
    return coordinate_.size();
  }
  /**
   * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
   */
  public LockstepProto.Coordinate getCoordinate(int index) {
    return coordinate_.get(index);
  }
  /**
   * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
   */
  public LockstepProto.CoordinateOrBuilder getCoordinateOrBuilder(
      int index) {
    return coordinate_.get(index);
  }

  public static final int SELECTION_FIELD_NUMBER = 5;
  private java.util.List<LockstepProto.Selection> selection_;
  /**
   * <code>repeated .LockstepProto.Selection selection = 5;</code>
   */
  public java.util.List<LockstepProto.Selection> getSelectionList() {
    return selection_;
  }
  /**
   * <code>repeated .LockstepProto.Selection selection = 5;</code>
   */
  public java.util.List<? extends LockstepProto.SelectionOrBuilder> 
      getSelectionOrBuilderList() {
    return selection_;
  }
  /**
   * <code>repeated .LockstepProto.Selection selection = 5;</code>
   */
  public int getSelectionCount() {
    return selection_.size();
  }
  /**
   * <code>repeated .LockstepProto.Selection selection = 5;</code>
   */
  public LockstepProto.Selection getSelection(int index) {
    return selection_.get(index);
  }
  /**
   * <code>repeated .LockstepProto.Selection selection = 5;</code>
   */
  public LockstepProto.SelectionOrBuilder getSelectionOrBuilder(
      int index) {
    return selection_.get(index);
  }

  public static final int VECTOR2D_FIELD_NUMBER = 6;
  private java.util.List<LockstepProto.Vector2d> vector2D_;
  /**
   * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
   */
  public java.util.List<LockstepProto.Vector2d> getVector2DList() {
    return vector2D_;
  }
  /**
   * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
   */
  public java.util.List<? extends LockstepProto.Vector2dOrBuilder> 
      getVector2DOrBuilderList() {
    return vector2D_;
  }
  /**
   * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
   */
  public int getVector2DCount() {
    return vector2D_.size();
  }
  /**
   * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
   */
  public LockstepProto.Vector2d getVector2D(int index) {
    return vector2D_.get(index);
  }
  /**
   * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
   */
  public LockstepProto.Vector2dOrBuilder getVector2DOrBuilder(
      int index) {
    return vector2D_.get(index);
  }

  public static final int VECTOR3D_FIELD_NUMBER = 7;
  private java.util.List<LockstepProto.Vector3d> vector3D_;
  /**
   * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
   */
  public java.util.List<LockstepProto.Vector3d> getVector3DList() {
    return vector3D_;
  }
  /**
   * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
   */
  public java.util.List<? extends LockstepProto.Vector3dOrBuilder> 
      getVector3DOrBuilderList() {
    return vector3D_;
  }
  /**
   * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
   */
  public int getVector3DCount() {
    return vector3D_.size();
  }
  /**
   * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
   */
  public LockstepProto.Vector3d getVector3D(int index) {
    return vector3D_.get(index);
  }
  /**
   * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
   */
  public LockstepProto.Vector3dOrBuilder getVector3DOrBuilder(
      int index) {
    return vector3D_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (controlerID_ != 0) {
      output.writeInt32(1, controlerID_);
    }
    if (inputCode_ != 0) {
      output.writeInt32(2, inputCode_);
    }
    for (int i = 0; i < defaultData_.size(); i++) {
      output.writeMessage(3, defaultData_.get(i));
    }
    for (int i = 0; i < coordinate_.size(); i++) {
      output.writeMessage(4, coordinate_.get(i));
    }
    for (int i = 0; i < selection_.size(); i++) {
      output.writeMessage(5, selection_.get(i));
    }
    for (int i = 0; i < vector2D_.size(); i++) {
      output.writeMessage(6, vector2D_.get(i));
    }
    for (int i = 0; i < vector3D_.size(); i++) {
      output.writeMessage(7, vector3D_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (controlerID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, controlerID_);
    }
    if (inputCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, inputCode_);
    }
    for (int i = 0; i < defaultData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, defaultData_.get(i));
    }
    for (int i = 0; i < coordinate_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, coordinate_.get(i));
    }
    for (int i = 0; i < selection_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, selection_.get(i));
    }
    for (int i = 0; i < vector2D_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, vector2D_.get(i));
    }
    for (int i = 0; i < vector3D_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, vector3D_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof LockstepProto.Command)) {
      return super.equals(obj);
    }
    LockstepProto.Command other = (LockstepProto.Command) obj;

    if (getControlerID()
        != other.getControlerID()) return false;
    if (getInputCode()
        != other.getInputCode()) return false;
    if (!getDefaultDataList()
        .equals(other.getDefaultDataList())) return false;
    if (!getCoordinateList()
        .equals(other.getCoordinateList())) return false;
    if (!getSelectionList()
        .equals(other.getSelectionList())) return false;
    if (!getVector2DList()
        .equals(other.getVector2DList())) return false;
    if (!getVector3DList()
        .equals(other.getVector3DList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTROLERID_FIELD_NUMBER;
    hash = (53 * hash) + getControlerID();
    hash = (37 * hash) + INPUTCODE_FIELD_NUMBER;
    hash = (53 * hash) + getInputCode();
    if (getDefaultDataCount() > 0) {
      hash = (37 * hash) + DEFAULTDATA_FIELD_NUMBER;
      hash = (53 * hash) + getDefaultDataList().hashCode();
    }
    if (getCoordinateCount() > 0) {
      hash = (37 * hash) + COORDINATE_FIELD_NUMBER;
      hash = (53 * hash) + getCoordinateList().hashCode();
    }
    if (getSelectionCount() > 0) {
      hash = (37 * hash) + SELECTION_FIELD_NUMBER;
      hash = (53 * hash) + getSelectionList().hashCode();
    }
    if (getVector2DCount() > 0) {
      hash = (37 * hash) + VECTOR2D_FIELD_NUMBER;
      hash = (53 * hash) + getVector2DList().hashCode();
    }
    if (getVector3DCount() > 0) {
      hash = (37 * hash) + VECTOR3D_FIELD_NUMBER;
      hash = (53 * hash) + getVector3DList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static LockstepProto.Command parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LockstepProto.Command parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LockstepProto.Command parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LockstepProto.Command parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LockstepProto.Command parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LockstepProto.Command parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LockstepProto.Command parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LockstepProto.Command parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static LockstepProto.Command parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static LockstepProto.Command parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static LockstepProto.Command parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LockstepProto.Command parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(LockstepProto.Command prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code LockstepProto.Command}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LockstepProto.Command)
      LockstepProto.CommandOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LockstepProto.LSMessage.internal_static_LockstepProto_Command_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LockstepProto.LSMessage.internal_static_LockstepProto_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LockstepProto.Command.class, LockstepProto.Command.Builder.class);
    }

    // Construct using LockstepProto.Command.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDefaultDataFieldBuilder();
        getCoordinateFieldBuilder();
        getSelectionFieldBuilder();
        getVector2DFieldBuilder();
        getVector3DFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      controlerID_ = 0;

      inputCode_ = 0;

      if (defaultDataBuilder_ == null) {
        defaultData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        defaultDataBuilder_.clear();
      }
      if (coordinateBuilder_ == null) {
        coordinate_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        coordinateBuilder_.clear();
      }
      if (selectionBuilder_ == null) {
        selection_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        selectionBuilder_.clear();
      }
      if (vector2DBuilder_ == null) {
        vector2D_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        vector2DBuilder_.clear();
      }
      if (vector3DBuilder_ == null) {
        vector3D_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        vector3DBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return LockstepProto.LSMessage.internal_static_LockstepProto_Command_descriptor;
    }

    @java.lang.Override
    public LockstepProto.Command getDefaultInstanceForType() {
      return LockstepProto.Command.getDefaultInstance();
    }

    @java.lang.Override
    public LockstepProto.Command build() {
      LockstepProto.Command result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public LockstepProto.Command buildPartial() {
      LockstepProto.Command result = new LockstepProto.Command(this);
      int from_bitField0_ = bitField0_;
      result.controlerID_ = controlerID_;
      result.inputCode_ = inputCode_;
      if (defaultDataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          defaultData_ = java.util.Collections.unmodifiableList(defaultData_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.defaultData_ = defaultData_;
      } else {
        result.defaultData_ = defaultDataBuilder_.build();
      }
      if (coordinateBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          coordinate_ = java.util.Collections.unmodifiableList(coordinate_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.coordinate_ = coordinate_;
      } else {
        result.coordinate_ = coordinateBuilder_.build();
      }
      if (selectionBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          selection_ = java.util.Collections.unmodifiableList(selection_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.selection_ = selection_;
      } else {
        result.selection_ = selectionBuilder_.build();
      }
      if (vector2DBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          vector2D_ = java.util.Collections.unmodifiableList(vector2D_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.vector2D_ = vector2D_;
      } else {
        result.vector2D_ = vector2DBuilder_.build();
      }
      if (vector3DBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          vector3D_ = java.util.Collections.unmodifiableList(vector3D_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.vector3D_ = vector3D_;
      } else {
        result.vector3D_ = vector3DBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof LockstepProto.Command) {
        return mergeFrom((LockstepProto.Command)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(LockstepProto.Command other) {
      if (other == LockstepProto.Command.getDefaultInstance()) return this;
      if (other.getControlerID() != 0) {
        setControlerID(other.getControlerID());
      }
      if (other.getInputCode() != 0) {
        setInputCode(other.getInputCode());
      }
      if (defaultDataBuilder_ == null) {
        if (!other.defaultData_.isEmpty()) {
          if (defaultData_.isEmpty()) {
            defaultData_ = other.defaultData_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDefaultDataIsMutable();
            defaultData_.addAll(other.defaultData_);
          }
          onChanged();
        }
      } else {
        if (!other.defaultData_.isEmpty()) {
          if (defaultDataBuilder_.isEmpty()) {
            defaultDataBuilder_.dispose();
            defaultDataBuilder_ = null;
            defaultData_ = other.defaultData_;
            bitField0_ = (bitField0_ & ~0x00000001);
            defaultDataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDefaultDataFieldBuilder() : null;
          } else {
            defaultDataBuilder_.addAllMessages(other.defaultData_);
          }
        }
      }
      if (coordinateBuilder_ == null) {
        if (!other.coordinate_.isEmpty()) {
          if (coordinate_.isEmpty()) {
            coordinate_ = other.coordinate_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureCoordinateIsMutable();
            coordinate_.addAll(other.coordinate_);
          }
          onChanged();
        }
      } else {
        if (!other.coordinate_.isEmpty()) {
          if (coordinateBuilder_.isEmpty()) {
            coordinateBuilder_.dispose();
            coordinateBuilder_ = null;
            coordinate_ = other.coordinate_;
            bitField0_ = (bitField0_ & ~0x00000002);
            coordinateBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCoordinateFieldBuilder() : null;
          } else {
            coordinateBuilder_.addAllMessages(other.coordinate_);
          }
        }
      }
      if (selectionBuilder_ == null) {
        if (!other.selection_.isEmpty()) {
          if (selection_.isEmpty()) {
            selection_ = other.selection_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSelectionIsMutable();
            selection_.addAll(other.selection_);
          }
          onChanged();
        }
      } else {
        if (!other.selection_.isEmpty()) {
          if (selectionBuilder_.isEmpty()) {
            selectionBuilder_.dispose();
            selectionBuilder_ = null;
            selection_ = other.selection_;
            bitField0_ = (bitField0_ & ~0x00000004);
            selectionBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSelectionFieldBuilder() : null;
          } else {
            selectionBuilder_.addAllMessages(other.selection_);
          }
        }
      }
      if (vector2DBuilder_ == null) {
        if (!other.vector2D_.isEmpty()) {
          if (vector2D_.isEmpty()) {
            vector2D_ = other.vector2D_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureVector2DIsMutable();
            vector2D_.addAll(other.vector2D_);
          }
          onChanged();
        }
      } else {
        if (!other.vector2D_.isEmpty()) {
          if (vector2DBuilder_.isEmpty()) {
            vector2DBuilder_.dispose();
            vector2DBuilder_ = null;
            vector2D_ = other.vector2D_;
            bitField0_ = (bitField0_ & ~0x00000008);
            vector2DBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVector2DFieldBuilder() : null;
          } else {
            vector2DBuilder_.addAllMessages(other.vector2D_);
          }
        }
      }
      if (vector3DBuilder_ == null) {
        if (!other.vector3D_.isEmpty()) {
          if (vector3D_.isEmpty()) {
            vector3D_ = other.vector3D_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureVector3DIsMutable();
            vector3D_.addAll(other.vector3D_);
          }
          onChanged();
        }
      } else {
        if (!other.vector3D_.isEmpty()) {
          if (vector3DBuilder_.isEmpty()) {
            vector3DBuilder_.dispose();
            vector3DBuilder_ = null;
            vector3D_ = other.vector3D_;
            bitField0_ = (bitField0_ & ~0x00000010);
            vector3DBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVector3DFieldBuilder() : null;
          } else {
            vector3DBuilder_.addAllMessages(other.vector3D_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      LockstepProto.Command parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (LockstepProto.Command) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int controlerID_ ;
    /**
     * <code>int32 controlerID = 1;</code>
     */
    public int getControlerID() {
      return controlerID_;
    }
    /**
     * <code>int32 controlerID = 1;</code>
     */
    public Builder setControlerID(int value) {
      
      controlerID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 controlerID = 1;</code>
     */
    public Builder clearControlerID() {
      
      controlerID_ = 0;
      onChanged();
      return this;
    }

    private int inputCode_ ;
    /**
     * <code>int32 inputCode = 2;</code>
     */
    public int getInputCode() {
      return inputCode_;
    }
    /**
     * <code>int32 inputCode = 2;</code>
     */
    public Builder setInputCode(int value) {
      
      inputCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 inputCode = 2;</code>
     */
    public Builder clearInputCode() {
      
      inputCode_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<LockstepProto.DefaultData> defaultData_ =
      java.util.Collections.emptyList();
    private void ensureDefaultDataIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        defaultData_ = new java.util.ArrayList<LockstepProto.DefaultData>(defaultData_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        LockstepProto.DefaultData, LockstepProto.DefaultData.Builder, LockstepProto.DefaultDataOrBuilder> defaultDataBuilder_;

    /**
     * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
     */
    public java.util.List<LockstepProto.DefaultData> getDefaultDataList() {
      if (defaultDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(defaultData_);
      } else {
        return defaultDataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
     */
    public int getDefaultDataCount() {
      if (defaultDataBuilder_ == null) {
        return defaultData_.size();
      } else {
        return defaultDataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
     */
    public LockstepProto.DefaultData getDefaultData(int index) {
      if (defaultDataBuilder_ == null) {
        return defaultData_.get(index);
      } else {
        return defaultDataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
     */
    public Builder setDefaultData(
        int index, LockstepProto.DefaultData value) {
      if (defaultDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDefaultDataIsMutable();
        defaultData_.set(index, value);
        onChanged();
      } else {
        defaultDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
     */
    public Builder setDefaultData(
        int index, LockstepProto.DefaultData.Builder builderForValue) {
      if (defaultDataBuilder_ == null) {
        ensureDefaultDataIsMutable();
        defaultData_.set(index, builderForValue.build());
        onChanged();
      } else {
        defaultDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
     */
    public Builder addDefaultData(LockstepProto.DefaultData value) {
      if (defaultDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDefaultDataIsMutable();
        defaultData_.add(value);
        onChanged();
      } else {
        defaultDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
     */
    public Builder addDefaultData(
        int index, LockstepProto.DefaultData value) {
      if (defaultDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDefaultDataIsMutable();
        defaultData_.add(index, value);
        onChanged();
      } else {
        defaultDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
     */
    public Builder addDefaultData(
        LockstepProto.DefaultData.Builder builderForValue) {
      if (defaultDataBuilder_ == null) {
        ensureDefaultDataIsMutable();
        defaultData_.add(builderForValue.build());
        onChanged();
      } else {
        defaultDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
     */
    public Builder addDefaultData(
        int index, LockstepProto.DefaultData.Builder builderForValue) {
      if (defaultDataBuilder_ == null) {
        ensureDefaultDataIsMutable();
        defaultData_.add(index, builderForValue.build());
        onChanged();
      } else {
        defaultDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
     */
    public Builder addAllDefaultData(
        java.lang.Iterable<? extends LockstepProto.DefaultData> values) {
      if (defaultDataBuilder_ == null) {
        ensureDefaultDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, defaultData_);
        onChanged();
      } else {
        defaultDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
     */
    public Builder clearDefaultData() {
      if (defaultDataBuilder_ == null) {
        defaultData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        defaultDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
     */
    public Builder removeDefaultData(int index) {
      if (defaultDataBuilder_ == null) {
        ensureDefaultDataIsMutable();
        defaultData_.remove(index);
        onChanged();
      } else {
        defaultDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
     */
    public LockstepProto.DefaultData.Builder getDefaultDataBuilder(
        int index) {
      return getDefaultDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
     */
    public LockstepProto.DefaultDataOrBuilder getDefaultDataOrBuilder(
        int index) {
      if (defaultDataBuilder_ == null) {
        return defaultData_.get(index);  } else {
        return defaultDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
     */
    public java.util.List<? extends LockstepProto.DefaultDataOrBuilder> 
         getDefaultDataOrBuilderList() {
      if (defaultDataBuilder_ != null) {
        return defaultDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(defaultData_);
      }
    }
    /**
     * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
     */
    public LockstepProto.DefaultData.Builder addDefaultDataBuilder() {
      return getDefaultDataFieldBuilder().addBuilder(
          LockstepProto.DefaultData.getDefaultInstance());
    }
    /**
     * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
     */
    public LockstepProto.DefaultData.Builder addDefaultDataBuilder(
        int index) {
      return getDefaultDataFieldBuilder().addBuilder(
          index, LockstepProto.DefaultData.getDefaultInstance());
    }
    /**
     * <code>repeated .LockstepProto.DefaultData defaultData = 3;</code>
     */
    public java.util.List<LockstepProto.DefaultData.Builder> 
         getDefaultDataBuilderList() {
      return getDefaultDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        LockstepProto.DefaultData, LockstepProto.DefaultData.Builder, LockstepProto.DefaultDataOrBuilder> 
        getDefaultDataFieldBuilder() {
      if (defaultDataBuilder_ == null) {
        defaultDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            LockstepProto.DefaultData, LockstepProto.DefaultData.Builder, LockstepProto.DefaultDataOrBuilder>(
                defaultData_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        defaultData_ = null;
      }
      return defaultDataBuilder_;
    }

    private java.util.List<LockstepProto.Coordinate> coordinate_ =
      java.util.Collections.emptyList();
    private void ensureCoordinateIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        coordinate_ = new java.util.ArrayList<LockstepProto.Coordinate>(coordinate_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        LockstepProto.Coordinate, LockstepProto.Coordinate.Builder, LockstepProto.CoordinateOrBuilder> coordinateBuilder_;

    /**
     * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
     */
    public java.util.List<LockstepProto.Coordinate> getCoordinateList() {
      if (coordinateBuilder_ == null) {
        return java.util.Collections.unmodifiableList(coordinate_);
      } else {
        return coordinateBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
     */
    public int getCoordinateCount() {
      if (coordinateBuilder_ == null) {
        return coordinate_.size();
      } else {
        return coordinateBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
     */
    public LockstepProto.Coordinate getCoordinate(int index) {
      if (coordinateBuilder_ == null) {
        return coordinate_.get(index);
      } else {
        return coordinateBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
     */
    public Builder setCoordinate(
        int index, LockstepProto.Coordinate value) {
      if (coordinateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoordinateIsMutable();
        coordinate_.set(index, value);
        onChanged();
      } else {
        coordinateBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
     */
    public Builder setCoordinate(
        int index, LockstepProto.Coordinate.Builder builderForValue) {
      if (coordinateBuilder_ == null) {
        ensureCoordinateIsMutable();
        coordinate_.set(index, builderForValue.build());
        onChanged();
      } else {
        coordinateBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
     */
    public Builder addCoordinate(LockstepProto.Coordinate value) {
      if (coordinateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoordinateIsMutable();
        coordinate_.add(value);
        onChanged();
      } else {
        coordinateBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
     */
    public Builder addCoordinate(
        int index, LockstepProto.Coordinate value) {
      if (coordinateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoordinateIsMutable();
        coordinate_.add(index, value);
        onChanged();
      } else {
        coordinateBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
     */
    public Builder addCoordinate(
        LockstepProto.Coordinate.Builder builderForValue) {
      if (coordinateBuilder_ == null) {
        ensureCoordinateIsMutable();
        coordinate_.add(builderForValue.build());
        onChanged();
      } else {
        coordinateBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
     */
    public Builder addCoordinate(
        int index, LockstepProto.Coordinate.Builder builderForValue) {
      if (coordinateBuilder_ == null) {
        ensureCoordinateIsMutable();
        coordinate_.add(index, builderForValue.build());
        onChanged();
      } else {
        coordinateBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
     */
    public Builder addAllCoordinate(
        java.lang.Iterable<? extends LockstepProto.Coordinate> values) {
      if (coordinateBuilder_ == null) {
        ensureCoordinateIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, coordinate_);
        onChanged();
      } else {
        coordinateBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
     */
    public Builder clearCoordinate() {
      if (coordinateBuilder_ == null) {
        coordinate_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        coordinateBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
     */
    public Builder removeCoordinate(int index) {
      if (coordinateBuilder_ == null) {
        ensureCoordinateIsMutable();
        coordinate_.remove(index);
        onChanged();
      } else {
        coordinateBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
     */
    public LockstepProto.Coordinate.Builder getCoordinateBuilder(
        int index) {
      return getCoordinateFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
     */
    public LockstepProto.CoordinateOrBuilder getCoordinateOrBuilder(
        int index) {
      if (coordinateBuilder_ == null) {
        return coordinate_.get(index);  } else {
        return coordinateBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
     */
    public java.util.List<? extends LockstepProto.CoordinateOrBuilder> 
         getCoordinateOrBuilderList() {
      if (coordinateBuilder_ != null) {
        return coordinateBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(coordinate_);
      }
    }
    /**
     * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
     */
    public LockstepProto.Coordinate.Builder addCoordinateBuilder() {
      return getCoordinateFieldBuilder().addBuilder(
          LockstepProto.Coordinate.getDefaultInstance());
    }
    /**
     * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
     */
    public LockstepProto.Coordinate.Builder addCoordinateBuilder(
        int index) {
      return getCoordinateFieldBuilder().addBuilder(
          index, LockstepProto.Coordinate.getDefaultInstance());
    }
    /**
     * <code>repeated .LockstepProto.Coordinate coordinate = 4;</code>
     */
    public java.util.List<LockstepProto.Coordinate.Builder> 
         getCoordinateBuilderList() {
      return getCoordinateFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        LockstepProto.Coordinate, LockstepProto.Coordinate.Builder, LockstepProto.CoordinateOrBuilder> 
        getCoordinateFieldBuilder() {
      if (coordinateBuilder_ == null) {
        coordinateBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            LockstepProto.Coordinate, LockstepProto.Coordinate.Builder, LockstepProto.CoordinateOrBuilder>(
                coordinate_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        coordinate_ = null;
      }
      return coordinateBuilder_;
    }

    private java.util.List<LockstepProto.Selection> selection_ =
      java.util.Collections.emptyList();
    private void ensureSelectionIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        selection_ = new java.util.ArrayList<LockstepProto.Selection>(selection_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        LockstepProto.Selection, LockstepProto.Selection.Builder, LockstepProto.SelectionOrBuilder> selectionBuilder_;

    /**
     * <code>repeated .LockstepProto.Selection selection = 5;</code>
     */
    public java.util.List<LockstepProto.Selection> getSelectionList() {
      if (selectionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(selection_);
      } else {
        return selectionBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .LockstepProto.Selection selection = 5;</code>
     */
    public int getSelectionCount() {
      if (selectionBuilder_ == null) {
        return selection_.size();
      } else {
        return selectionBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .LockstepProto.Selection selection = 5;</code>
     */
    public LockstepProto.Selection getSelection(int index) {
      if (selectionBuilder_ == null) {
        return selection_.get(index);
      } else {
        return selectionBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .LockstepProto.Selection selection = 5;</code>
     */
    public Builder setSelection(
        int index, LockstepProto.Selection value) {
      if (selectionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSelectionIsMutable();
        selection_.set(index, value);
        onChanged();
      } else {
        selectionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Selection selection = 5;</code>
     */
    public Builder setSelection(
        int index, LockstepProto.Selection.Builder builderForValue) {
      if (selectionBuilder_ == null) {
        ensureSelectionIsMutable();
        selection_.set(index, builderForValue.build());
        onChanged();
      } else {
        selectionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Selection selection = 5;</code>
     */
    public Builder addSelection(LockstepProto.Selection value) {
      if (selectionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSelectionIsMutable();
        selection_.add(value);
        onChanged();
      } else {
        selectionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Selection selection = 5;</code>
     */
    public Builder addSelection(
        int index, LockstepProto.Selection value) {
      if (selectionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSelectionIsMutable();
        selection_.add(index, value);
        onChanged();
      } else {
        selectionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Selection selection = 5;</code>
     */
    public Builder addSelection(
        LockstepProto.Selection.Builder builderForValue) {
      if (selectionBuilder_ == null) {
        ensureSelectionIsMutable();
        selection_.add(builderForValue.build());
        onChanged();
      } else {
        selectionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Selection selection = 5;</code>
     */
    public Builder addSelection(
        int index, LockstepProto.Selection.Builder builderForValue) {
      if (selectionBuilder_ == null) {
        ensureSelectionIsMutable();
        selection_.add(index, builderForValue.build());
        onChanged();
      } else {
        selectionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Selection selection = 5;</code>
     */
    public Builder addAllSelection(
        java.lang.Iterable<? extends LockstepProto.Selection> values) {
      if (selectionBuilder_ == null) {
        ensureSelectionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, selection_);
        onChanged();
      } else {
        selectionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Selection selection = 5;</code>
     */
    public Builder clearSelection() {
      if (selectionBuilder_ == null) {
        selection_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        selectionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Selection selection = 5;</code>
     */
    public Builder removeSelection(int index) {
      if (selectionBuilder_ == null) {
        ensureSelectionIsMutable();
        selection_.remove(index);
        onChanged();
      } else {
        selectionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Selection selection = 5;</code>
     */
    public LockstepProto.Selection.Builder getSelectionBuilder(
        int index) {
      return getSelectionFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .LockstepProto.Selection selection = 5;</code>
     */
    public LockstepProto.SelectionOrBuilder getSelectionOrBuilder(
        int index) {
      if (selectionBuilder_ == null) {
        return selection_.get(index);  } else {
        return selectionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .LockstepProto.Selection selection = 5;</code>
     */
    public java.util.List<? extends LockstepProto.SelectionOrBuilder> 
         getSelectionOrBuilderList() {
      if (selectionBuilder_ != null) {
        return selectionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(selection_);
      }
    }
    /**
     * <code>repeated .LockstepProto.Selection selection = 5;</code>
     */
    public LockstepProto.Selection.Builder addSelectionBuilder() {
      return getSelectionFieldBuilder().addBuilder(
          LockstepProto.Selection.getDefaultInstance());
    }
    /**
     * <code>repeated .LockstepProto.Selection selection = 5;</code>
     */
    public LockstepProto.Selection.Builder addSelectionBuilder(
        int index) {
      return getSelectionFieldBuilder().addBuilder(
          index, LockstepProto.Selection.getDefaultInstance());
    }
    /**
     * <code>repeated .LockstepProto.Selection selection = 5;</code>
     */
    public java.util.List<LockstepProto.Selection.Builder> 
         getSelectionBuilderList() {
      return getSelectionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        LockstepProto.Selection, LockstepProto.Selection.Builder, LockstepProto.SelectionOrBuilder> 
        getSelectionFieldBuilder() {
      if (selectionBuilder_ == null) {
        selectionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            LockstepProto.Selection, LockstepProto.Selection.Builder, LockstepProto.SelectionOrBuilder>(
                selection_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        selection_ = null;
      }
      return selectionBuilder_;
    }

    private java.util.List<LockstepProto.Vector2d> vector2D_ =
      java.util.Collections.emptyList();
    private void ensureVector2DIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        vector2D_ = new java.util.ArrayList<LockstepProto.Vector2d>(vector2D_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        LockstepProto.Vector2d, LockstepProto.Vector2d.Builder, LockstepProto.Vector2dOrBuilder> vector2DBuilder_;

    /**
     * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
     */
    public java.util.List<LockstepProto.Vector2d> getVector2DList() {
      if (vector2DBuilder_ == null) {
        return java.util.Collections.unmodifiableList(vector2D_);
      } else {
        return vector2DBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
     */
    public int getVector2DCount() {
      if (vector2DBuilder_ == null) {
        return vector2D_.size();
      } else {
        return vector2DBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
     */
    public LockstepProto.Vector2d getVector2D(int index) {
      if (vector2DBuilder_ == null) {
        return vector2D_.get(index);
      } else {
        return vector2DBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
     */
    public Builder setVector2D(
        int index, LockstepProto.Vector2d value) {
      if (vector2DBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVector2DIsMutable();
        vector2D_.set(index, value);
        onChanged();
      } else {
        vector2DBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
     */
    public Builder setVector2D(
        int index, LockstepProto.Vector2d.Builder builderForValue) {
      if (vector2DBuilder_ == null) {
        ensureVector2DIsMutable();
        vector2D_.set(index, builderForValue.build());
        onChanged();
      } else {
        vector2DBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
     */
    public Builder addVector2D(LockstepProto.Vector2d value) {
      if (vector2DBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVector2DIsMutable();
        vector2D_.add(value);
        onChanged();
      } else {
        vector2DBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
     */
    public Builder addVector2D(
        int index, LockstepProto.Vector2d value) {
      if (vector2DBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVector2DIsMutable();
        vector2D_.add(index, value);
        onChanged();
      } else {
        vector2DBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
     */
    public Builder addVector2D(
        LockstepProto.Vector2d.Builder builderForValue) {
      if (vector2DBuilder_ == null) {
        ensureVector2DIsMutable();
        vector2D_.add(builderForValue.build());
        onChanged();
      } else {
        vector2DBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
     */
    public Builder addVector2D(
        int index, LockstepProto.Vector2d.Builder builderForValue) {
      if (vector2DBuilder_ == null) {
        ensureVector2DIsMutable();
        vector2D_.add(index, builderForValue.build());
        onChanged();
      } else {
        vector2DBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
     */
    public Builder addAllVector2D(
        java.lang.Iterable<? extends LockstepProto.Vector2d> values) {
      if (vector2DBuilder_ == null) {
        ensureVector2DIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, vector2D_);
        onChanged();
      } else {
        vector2DBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
     */
    public Builder clearVector2D() {
      if (vector2DBuilder_ == null) {
        vector2D_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        vector2DBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
     */
    public Builder removeVector2D(int index) {
      if (vector2DBuilder_ == null) {
        ensureVector2DIsMutable();
        vector2D_.remove(index);
        onChanged();
      } else {
        vector2DBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
     */
    public LockstepProto.Vector2d.Builder getVector2DBuilder(
        int index) {
      return getVector2DFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
     */
    public LockstepProto.Vector2dOrBuilder getVector2DOrBuilder(
        int index) {
      if (vector2DBuilder_ == null) {
        return vector2D_.get(index);  } else {
        return vector2DBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
     */
    public java.util.List<? extends LockstepProto.Vector2dOrBuilder> 
         getVector2DOrBuilderList() {
      if (vector2DBuilder_ != null) {
        return vector2DBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(vector2D_);
      }
    }
    /**
     * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
     */
    public LockstepProto.Vector2d.Builder addVector2DBuilder() {
      return getVector2DFieldBuilder().addBuilder(
          LockstepProto.Vector2d.getDefaultInstance());
    }
    /**
     * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
     */
    public LockstepProto.Vector2d.Builder addVector2DBuilder(
        int index) {
      return getVector2DFieldBuilder().addBuilder(
          index, LockstepProto.Vector2d.getDefaultInstance());
    }
    /**
     * <code>repeated .LockstepProto.Vector2d vector2d = 6;</code>
     */
    public java.util.List<LockstepProto.Vector2d.Builder> 
         getVector2DBuilderList() {
      return getVector2DFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        LockstepProto.Vector2d, LockstepProto.Vector2d.Builder, LockstepProto.Vector2dOrBuilder> 
        getVector2DFieldBuilder() {
      if (vector2DBuilder_ == null) {
        vector2DBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            LockstepProto.Vector2d, LockstepProto.Vector2d.Builder, LockstepProto.Vector2dOrBuilder>(
                vector2D_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        vector2D_ = null;
      }
      return vector2DBuilder_;
    }

    private java.util.List<LockstepProto.Vector3d> vector3D_ =
      java.util.Collections.emptyList();
    private void ensureVector3DIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        vector3D_ = new java.util.ArrayList<LockstepProto.Vector3d>(vector3D_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        LockstepProto.Vector3d, LockstepProto.Vector3d.Builder, LockstepProto.Vector3dOrBuilder> vector3DBuilder_;

    /**
     * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
     */
    public java.util.List<LockstepProto.Vector3d> getVector3DList() {
      if (vector3DBuilder_ == null) {
        return java.util.Collections.unmodifiableList(vector3D_);
      } else {
        return vector3DBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
     */
    public int getVector3DCount() {
      if (vector3DBuilder_ == null) {
        return vector3D_.size();
      } else {
        return vector3DBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
     */
    public LockstepProto.Vector3d getVector3D(int index) {
      if (vector3DBuilder_ == null) {
        return vector3D_.get(index);
      } else {
        return vector3DBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
     */
    public Builder setVector3D(
        int index, LockstepProto.Vector3d value) {
      if (vector3DBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVector3DIsMutable();
        vector3D_.set(index, value);
        onChanged();
      } else {
        vector3DBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
     */
    public Builder setVector3D(
        int index, LockstepProto.Vector3d.Builder builderForValue) {
      if (vector3DBuilder_ == null) {
        ensureVector3DIsMutable();
        vector3D_.set(index, builderForValue.build());
        onChanged();
      } else {
        vector3DBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
     */
    public Builder addVector3D(LockstepProto.Vector3d value) {
      if (vector3DBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVector3DIsMutable();
        vector3D_.add(value);
        onChanged();
      } else {
        vector3DBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
     */
    public Builder addVector3D(
        int index, LockstepProto.Vector3d value) {
      if (vector3DBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVector3DIsMutable();
        vector3D_.add(index, value);
        onChanged();
      } else {
        vector3DBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
     */
    public Builder addVector3D(
        LockstepProto.Vector3d.Builder builderForValue) {
      if (vector3DBuilder_ == null) {
        ensureVector3DIsMutable();
        vector3D_.add(builderForValue.build());
        onChanged();
      } else {
        vector3DBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
     */
    public Builder addVector3D(
        int index, LockstepProto.Vector3d.Builder builderForValue) {
      if (vector3DBuilder_ == null) {
        ensureVector3DIsMutable();
        vector3D_.add(index, builderForValue.build());
        onChanged();
      } else {
        vector3DBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
     */
    public Builder addAllVector3D(
        java.lang.Iterable<? extends LockstepProto.Vector3d> values) {
      if (vector3DBuilder_ == null) {
        ensureVector3DIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, vector3D_);
        onChanged();
      } else {
        vector3DBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
     */
    public Builder clearVector3D() {
      if (vector3DBuilder_ == null) {
        vector3D_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        vector3DBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
     */
    public Builder removeVector3D(int index) {
      if (vector3DBuilder_ == null) {
        ensureVector3DIsMutable();
        vector3D_.remove(index);
        onChanged();
      } else {
        vector3DBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
     */
    public LockstepProto.Vector3d.Builder getVector3DBuilder(
        int index) {
      return getVector3DFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
     */
    public LockstepProto.Vector3dOrBuilder getVector3DOrBuilder(
        int index) {
      if (vector3DBuilder_ == null) {
        return vector3D_.get(index);  } else {
        return vector3DBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
     */
    public java.util.List<? extends LockstepProto.Vector3dOrBuilder> 
         getVector3DOrBuilderList() {
      if (vector3DBuilder_ != null) {
        return vector3DBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(vector3D_);
      }
    }
    /**
     * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
     */
    public LockstepProto.Vector3d.Builder addVector3DBuilder() {
      return getVector3DFieldBuilder().addBuilder(
          LockstepProto.Vector3d.getDefaultInstance());
    }
    /**
     * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
     */
    public LockstepProto.Vector3d.Builder addVector3DBuilder(
        int index) {
      return getVector3DFieldBuilder().addBuilder(
          index, LockstepProto.Vector3d.getDefaultInstance());
    }
    /**
     * <code>repeated .LockstepProto.Vector3d vector3d = 7;</code>
     */
    public java.util.List<LockstepProto.Vector3d.Builder> 
         getVector3DBuilderList() {
      return getVector3DFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        LockstepProto.Vector3d, LockstepProto.Vector3d.Builder, LockstepProto.Vector3dOrBuilder> 
        getVector3DFieldBuilder() {
      if (vector3DBuilder_ == null) {
        vector3DBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            LockstepProto.Vector3d, LockstepProto.Vector3d.Builder, LockstepProto.Vector3dOrBuilder>(
                vector3D_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        vector3D_ = null;
      }
      return vector3DBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:LockstepProto.Command)
  }

  // @@protoc_insertion_point(class_scope:LockstepProto.Command)
  private static final LockstepProto.Command DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new LockstepProto.Command();
  }

  public static LockstepProto.Command getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Command>
      PARSER = new com.google.protobuf.AbstractParser<Command>() {
    @java.lang.Override
    public Command parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Command(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Command> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Command> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public LockstepProto.Command getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

