// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetMessage.proto

package LockstepProto;

public interface S2CHeartBeatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LockstepProto.S2CHeartBeat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 seq = 1;</code>
   */
  int getSeq();
}
