// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgPlayer.proto

package com.lung.game.proto.msg;

public final class MsgPlayer {
  private MsgPlayer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CSLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lung.game.proto.msg.CSLogin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *玩家id
     * </pre>
     *
     * <code>string uid = 1;</code>
     * @return The uid.
     */
    java.lang.String getUid();
    /**
     * <pre>
     *玩家id
     * </pre>
     *
     * <code>string uid = 1;</code>
     * @return The bytes for uid.
     */
    com.google.protobuf.ByteString
        getUidBytes();
  }
  /**
   * <pre>
   * -----------------------------------------
   * 玩家相关
   * -----------------------------------------
   * 请求登录
   * </pre>
   *
   * Protobuf type {@code com.lung.game.proto.msg.CSLogin}
   */
  public static final class CSLogin extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.lung.game.proto.msg.CSLogin)
      CSLoginOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CSLogin.newBuilder() to construct.
    private CSLogin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CSLogin() {
      uid_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CSLogin();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CSLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lung.game.proto.msg.MsgPlayer.internal_static_com_lung_game_proto_msg_CSLogin_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lung.game.proto.msg.MsgPlayer.internal_static_com_lung_game_proto_msg_CSLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lung.game.proto.msg.MsgPlayer.CSLogin.class, com.lung.game.proto.msg.MsgPlayer.CSLogin.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uid_;
    /**
     * <pre>
     *玩家id
     * </pre>
     *
     * <code>string uid = 1;</code>
     * @return The uid.
     */
    @java.lang.Override
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *玩家id
     * </pre>
     *
     * <code>string uid = 1;</code>
     * @return The bytes for uid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lung.game.proto.msg.MsgPlayer.CSLogin)) {
        return super.equals(obj);
      }
      com.lung.game.proto.msg.MsgPlayer.CSLogin other = (com.lung.game.proto.msg.MsgPlayer.CSLogin) obj;

      if (!getUid()
          .equals(other.getUid())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lung.game.proto.msg.MsgPlayer.CSLogin parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lung.game.proto.msg.MsgPlayer.CSLogin parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lung.game.proto.msg.MsgPlayer.CSLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lung.game.proto.msg.MsgPlayer.CSLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lung.game.proto.msg.MsgPlayer.CSLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lung.game.proto.msg.MsgPlayer.CSLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lung.game.proto.msg.MsgPlayer.CSLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lung.game.proto.msg.MsgPlayer.CSLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lung.game.proto.msg.MsgPlayer.CSLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lung.game.proto.msg.MsgPlayer.CSLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lung.game.proto.msg.MsgPlayer.CSLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lung.game.proto.msg.MsgPlayer.CSLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lung.game.proto.msg.MsgPlayer.CSLogin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * -----------------------------------------
     * 玩家相关
     * -----------------------------------------
     * 请求登录
     * </pre>
     *
     * Protobuf type {@code com.lung.game.proto.msg.CSLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lung.game.proto.msg.CSLogin)
        com.lung.game.proto.msg.MsgPlayer.CSLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lung.game.proto.msg.MsgPlayer.internal_static_com_lung_game_proto_msg_CSLogin_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lung.game.proto.msg.MsgPlayer.internal_static_com_lung_game_proto_msg_CSLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lung.game.proto.msg.MsgPlayer.CSLogin.class, com.lung.game.proto.msg.MsgPlayer.CSLogin.Builder.class);
      }

      // Construct using com.lung.game.proto.msg.MsgPlayer.CSLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uid_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lung.game.proto.msg.MsgPlayer.internal_static_com_lung_game_proto_msg_CSLogin_descriptor;
      }

      @java.lang.Override
      public com.lung.game.proto.msg.MsgPlayer.CSLogin getDefaultInstanceForType() {
        return com.lung.game.proto.msg.MsgPlayer.CSLogin.getDefaultInstance();
      }

      @java.lang.Override
      public com.lung.game.proto.msg.MsgPlayer.CSLogin build() {
        com.lung.game.proto.msg.MsgPlayer.CSLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lung.game.proto.msg.MsgPlayer.CSLogin buildPartial() {
        com.lung.game.proto.msg.MsgPlayer.CSLogin result = new com.lung.game.proto.msg.MsgPlayer.CSLogin(this);
        result.uid_ = uid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lung.game.proto.msg.MsgPlayer.CSLogin) {
          return mergeFrom((com.lung.game.proto.msg.MsgPlayer.CSLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lung.game.proto.msg.MsgPlayer.CSLogin other) {
        if (other == com.lung.game.proto.msg.MsgPlayer.CSLogin.getDefaultInstance()) return this;
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lung.game.proto.msg.MsgPlayer.CSLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lung.game.proto.msg.MsgPlayer.CSLogin) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uid_ = "";
      /**
       * <pre>
       *玩家id
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @return The uid.
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *玩家id
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @return The bytes for uid.
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *玩家id
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *玩家id
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *玩家id
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @param value The bytes for uid to set.
       * @return This builder for chaining.
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uid_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.lung.game.proto.msg.CSLogin)
    }

    // @@protoc_insertion_point(class_scope:com.lung.game.proto.msg.CSLogin)
    private static final com.lung.game.proto.msg.MsgPlayer.CSLogin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lung.game.proto.msg.MsgPlayer.CSLogin();
    }

    public static com.lung.game.proto.msg.MsgPlayer.CSLogin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CSLogin>
        PARSER = new com.google.protobuf.AbstractParser<CSLogin>() {
      @java.lang.Override
      public CSLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSLogin(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CSLogin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CSLogin> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lung.game.proto.msg.MsgPlayer.CSLogin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SCLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lung.game.proto.msg.SCLogin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *token信息
     * </pre>
     *
     * <code>string token = 1;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <pre>
     *token信息
     * </pre>
     *
     * <code>string token = 1;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <pre>
     *token信息
     * </pre>
     *
     * <code>.com.lung.game.proto.msg.UserInfo userInfo = 2;</code>
     * @return Whether the userInfo field is set.
     */
    boolean hasUserInfo();
    /**
     * <pre>
     *token信息
     * </pre>
     *
     * <code>.com.lung.game.proto.msg.UserInfo userInfo = 2;</code>
     * @return The userInfo.
     */
    com.lung.game.proto.msg.MsgDef.UserInfo getUserInfo();
    /**
     * <pre>
     *token信息
     * </pre>
     *
     * <code>.com.lung.game.proto.msg.UserInfo userInfo = 2;</code>
     */
    com.lung.game.proto.msg.MsgDef.UserInfoOrBuilder getUserInfoOrBuilder();
  }
  /**
   * <pre>
   * 响应登录
   * </pre>
   *
   * Protobuf type {@code com.lung.game.proto.msg.SCLogin}
   */
  public static final class SCLogin extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.lung.game.proto.msg.SCLogin)
      SCLoginOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SCLogin.newBuilder() to construct.
    private SCLogin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SCLogin() {
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SCLogin();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SCLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 18: {
              com.lung.game.proto.msg.MsgDef.UserInfo.Builder subBuilder = null;
              if (userInfo_ != null) {
                subBuilder = userInfo_.toBuilder();
              }
              userInfo_ = input.readMessage(com.lung.game.proto.msg.MsgDef.UserInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userInfo_);
                userInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lung.game.proto.msg.MsgPlayer.internal_static_com_lung_game_proto_msg_SCLogin_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lung.game.proto.msg.MsgPlayer.internal_static_com_lung_game_proto_msg_SCLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lung.game.proto.msg.MsgPlayer.SCLogin.class, com.lung.game.proto.msg.MsgPlayer.SCLogin.Builder.class);
    }

    public static final int TOKEN_FIELD_NUMBER = 1;
    private volatile java.lang.Object token_;
    /**
     * <pre>
     *token信息
     * </pre>
     *
     * <code>string token = 1;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *token信息
     * </pre>
     *
     * <code>string token = 1;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERINFO_FIELD_NUMBER = 2;
    private com.lung.game.proto.msg.MsgDef.UserInfo userInfo_;
    /**
     * <pre>
     *token信息
     * </pre>
     *
     * <code>.com.lung.game.proto.msg.UserInfo userInfo = 2;</code>
     * @return Whether the userInfo field is set.
     */
    @java.lang.Override
    public boolean hasUserInfo() {
      return userInfo_ != null;
    }
    /**
     * <pre>
     *token信息
     * </pre>
     *
     * <code>.com.lung.game.proto.msg.UserInfo userInfo = 2;</code>
     * @return The userInfo.
     */
    @java.lang.Override
    public com.lung.game.proto.msg.MsgDef.UserInfo getUserInfo() {
      return userInfo_ == null ? com.lung.game.proto.msg.MsgDef.UserInfo.getDefaultInstance() : userInfo_;
    }
    /**
     * <pre>
     *token信息
     * </pre>
     *
     * <code>.com.lung.game.proto.msg.UserInfo userInfo = 2;</code>
     */
    @java.lang.Override
    public com.lung.game.proto.msg.MsgDef.UserInfoOrBuilder getUserInfoOrBuilder() {
      return getUserInfo();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, token_);
      }
      if (userInfo_ != null) {
        output.writeMessage(2, getUserInfo());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, token_);
      }
      if (userInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getUserInfo());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lung.game.proto.msg.MsgPlayer.SCLogin)) {
        return super.equals(obj);
      }
      com.lung.game.proto.msg.MsgPlayer.SCLogin other = (com.lung.game.proto.msg.MsgPlayer.SCLogin) obj;

      if (!getToken()
          .equals(other.getToken())) return false;
      if (hasUserInfo() != other.hasUserInfo()) return false;
      if (hasUserInfo()) {
        if (!getUserInfo()
            .equals(other.getUserInfo())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      if (hasUserInfo()) {
        hash = (37 * hash) + USERINFO_FIELD_NUMBER;
        hash = (53 * hash) + getUserInfo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lung.game.proto.msg.MsgPlayer.SCLogin parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lung.game.proto.msg.MsgPlayer.SCLogin parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lung.game.proto.msg.MsgPlayer.SCLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lung.game.proto.msg.MsgPlayer.SCLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lung.game.proto.msg.MsgPlayer.SCLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lung.game.proto.msg.MsgPlayer.SCLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lung.game.proto.msg.MsgPlayer.SCLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lung.game.proto.msg.MsgPlayer.SCLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lung.game.proto.msg.MsgPlayer.SCLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lung.game.proto.msg.MsgPlayer.SCLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lung.game.proto.msg.MsgPlayer.SCLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lung.game.proto.msg.MsgPlayer.SCLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lung.game.proto.msg.MsgPlayer.SCLogin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 响应登录
     * </pre>
     *
     * Protobuf type {@code com.lung.game.proto.msg.SCLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lung.game.proto.msg.SCLogin)
        com.lung.game.proto.msg.MsgPlayer.SCLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lung.game.proto.msg.MsgPlayer.internal_static_com_lung_game_proto_msg_SCLogin_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lung.game.proto.msg.MsgPlayer.internal_static_com_lung_game_proto_msg_SCLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lung.game.proto.msg.MsgPlayer.SCLogin.class, com.lung.game.proto.msg.MsgPlayer.SCLogin.Builder.class);
      }

      // Construct using com.lung.game.proto.msg.MsgPlayer.SCLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        token_ = "";

        if (userInfoBuilder_ == null) {
          userInfo_ = null;
        } else {
          userInfo_ = null;
          userInfoBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lung.game.proto.msg.MsgPlayer.internal_static_com_lung_game_proto_msg_SCLogin_descriptor;
      }

      @java.lang.Override
      public com.lung.game.proto.msg.MsgPlayer.SCLogin getDefaultInstanceForType() {
        return com.lung.game.proto.msg.MsgPlayer.SCLogin.getDefaultInstance();
      }

      @java.lang.Override
      public com.lung.game.proto.msg.MsgPlayer.SCLogin build() {
        com.lung.game.proto.msg.MsgPlayer.SCLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lung.game.proto.msg.MsgPlayer.SCLogin buildPartial() {
        com.lung.game.proto.msg.MsgPlayer.SCLogin result = new com.lung.game.proto.msg.MsgPlayer.SCLogin(this);
        result.token_ = token_;
        if (userInfoBuilder_ == null) {
          result.userInfo_ = userInfo_;
        } else {
          result.userInfo_ = userInfoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lung.game.proto.msg.MsgPlayer.SCLogin) {
          return mergeFrom((com.lung.game.proto.msg.MsgPlayer.SCLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lung.game.proto.msg.MsgPlayer.SCLogin other) {
        if (other == com.lung.game.proto.msg.MsgPlayer.SCLogin.getDefaultInstance()) return this;
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.hasUserInfo()) {
          mergeUserInfo(other.getUserInfo());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lung.game.proto.msg.MsgPlayer.SCLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lung.game.proto.msg.MsgPlayer.SCLogin) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <pre>
       *token信息
       * </pre>
       *
       * <code>string token = 1;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *token信息
       * </pre>
       *
       * <code>string token = 1;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *token信息
       * </pre>
       *
       * <code>string token = 1;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *token信息
       * </pre>
       *
       * <code>string token = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *token信息
       * </pre>
       *
       * <code>string token = 1;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private com.lung.game.proto.msg.MsgDef.UserInfo userInfo_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.lung.game.proto.msg.MsgDef.UserInfo, com.lung.game.proto.msg.MsgDef.UserInfo.Builder, com.lung.game.proto.msg.MsgDef.UserInfoOrBuilder> userInfoBuilder_;
      /**
       * <pre>
       *token信息
       * </pre>
       *
       * <code>.com.lung.game.proto.msg.UserInfo userInfo = 2;</code>
       * @return Whether the userInfo field is set.
       */
      public boolean hasUserInfo() {
        return userInfoBuilder_ != null || userInfo_ != null;
      }
      /**
       * <pre>
       *token信息
       * </pre>
       *
       * <code>.com.lung.game.proto.msg.UserInfo userInfo = 2;</code>
       * @return The userInfo.
       */
      public com.lung.game.proto.msg.MsgDef.UserInfo getUserInfo() {
        if (userInfoBuilder_ == null) {
          return userInfo_ == null ? com.lung.game.proto.msg.MsgDef.UserInfo.getDefaultInstance() : userInfo_;
        } else {
          return userInfoBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *token信息
       * </pre>
       *
       * <code>.com.lung.game.proto.msg.UserInfo userInfo = 2;</code>
       */
      public Builder setUserInfo(com.lung.game.proto.msg.MsgDef.UserInfo value) {
        if (userInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userInfo_ = value;
          onChanged();
        } else {
          userInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *token信息
       * </pre>
       *
       * <code>.com.lung.game.proto.msg.UserInfo userInfo = 2;</code>
       */
      public Builder setUserInfo(
          com.lung.game.proto.msg.MsgDef.UserInfo.Builder builderForValue) {
        if (userInfoBuilder_ == null) {
          userInfo_ = builderForValue.build();
          onChanged();
        } else {
          userInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *token信息
       * </pre>
       *
       * <code>.com.lung.game.proto.msg.UserInfo userInfo = 2;</code>
       */
      public Builder mergeUserInfo(com.lung.game.proto.msg.MsgDef.UserInfo value) {
        if (userInfoBuilder_ == null) {
          if (userInfo_ != null) {
            userInfo_ =
              com.lung.game.proto.msg.MsgDef.UserInfo.newBuilder(userInfo_).mergeFrom(value).buildPartial();
          } else {
            userInfo_ = value;
          }
          onChanged();
        } else {
          userInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *token信息
       * </pre>
       *
       * <code>.com.lung.game.proto.msg.UserInfo userInfo = 2;</code>
       */
      public Builder clearUserInfo() {
        if (userInfoBuilder_ == null) {
          userInfo_ = null;
          onChanged();
        } else {
          userInfo_ = null;
          userInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *token信息
       * </pre>
       *
       * <code>.com.lung.game.proto.msg.UserInfo userInfo = 2;</code>
       */
      public com.lung.game.proto.msg.MsgDef.UserInfo.Builder getUserInfoBuilder() {
        
        onChanged();
        return getUserInfoFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *token信息
       * </pre>
       *
       * <code>.com.lung.game.proto.msg.UserInfo userInfo = 2;</code>
       */
      public com.lung.game.proto.msg.MsgDef.UserInfoOrBuilder getUserInfoOrBuilder() {
        if (userInfoBuilder_ != null) {
          return userInfoBuilder_.getMessageOrBuilder();
        } else {
          return userInfo_ == null ?
              com.lung.game.proto.msg.MsgDef.UserInfo.getDefaultInstance() : userInfo_;
        }
      }
      /**
       * <pre>
       *token信息
       * </pre>
       *
       * <code>.com.lung.game.proto.msg.UserInfo userInfo = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.lung.game.proto.msg.MsgDef.UserInfo, com.lung.game.proto.msg.MsgDef.UserInfo.Builder, com.lung.game.proto.msg.MsgDef.UserInfoOrBuilder> 
          getUserInfoFieldBuilder() {
        if (userInfoBuilder_ == null) {
          userInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.lung.game.proto.msg.MsgDef.UserInfo, com.lung.game.proto.msg.MsgDef.UserInfo.Builder, com.lung.game.proto.msg.MsgDef.UserInfoOrBuilder>(
                  getUserInfo(),
                  getParentForChildren(),
                  isClean());
          userInfo_ = null;
        }
        return userInfoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.lung.game.proto.msg.SCLogin)
    }

    // @@protoc_insertion_point(class_scope:com.lung.game.proto.msg.SCLogin)
    private static final com.lung.game.proto.msg.MsgPlayer.SCLogin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lung.game.proto.msg.MsgPlayer.SCLogin();
    }

    public static com.lung.game.proto.msg.MsgPlayer.SCLogin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SCLogin>
        PARSER = new com.google.protobuf.AbstractParser<SCLogin>() {
      @java.lang.Override
      public SCLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SCLogin(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SCLogin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SCLogin> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lung.game.proto.msg.MsgPlayer.SCLogin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lung_game_proto_msg_CSLogin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lung_game_proto_msg_CSLogin_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lung_game_proto_msg_SCLogin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lung_game_proto_msg_SCLogin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017MsgPlayer.proto\022\027com.lung.game.proto.m" +
      "sg\032\roptions.proto\032\014MsgDef.proto\"\035\n\007CSLog" +
      "in\022\013\n\003uid\030\001 \001(\t:\005\220\202\031\261\t\"T\n\007SCLogin\022\r\n\005tok" +
      "en\030\001 \001(\t\0223\n\010userInfo\030\002 \001(\0132!.com.lung.ga" +
      "me.proto.msg.UserInfo:\005\220\202\031\262\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.noseparte.game.bean.proto.Options.getDescriptor(),
          com.lung.game.proto.msg.MsgDef.getDescriptor(),
        });
    internal_static_com_lung_game_proto_msg_CSLogin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lung_game_proto_msg_CSLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lung_game_proto_msg_CSLogin_descriptor,
        new java.lang.String[] { "Uid", });
    internal_static_com_lung_game_proto_msg_SCLogin_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_lung_game_proto_msg_SCLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lung_game_proto_msg_SCLogin_descriptor,
        new java.lang.String[] { "Token", "UserInfo", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.noseparte.game.bean.proto.Options.msgId);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.noseparte.game.bean.proto.Options.getDescriptor();
    com.lung.game.proto.msg.MsgDef.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
